[package]
name = "find-s"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.3", features = ["derive"] }
console = { version = "0.15.0"}
dialoguer = "0.10.0"
csv = "1.1"
serde = { version = "1", features = ["derive"] }